app/posts/models.py
""" models.py """

from datetime import datetime
from hashlib import sha1
from app import db


class Post(db.Model):
    """ Class Post """
    id            = db.Column(db.Integer, primary_key=True)
    ovner         = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    forward       = db.Column(db.Boolean, unique=False, default=False, nullable=False)
    title         = db.Column(db.String(256), default='', nullable=False)
    pub_date      = db.Column(db.DateTime, default=datetime.now())
    last_modified = db.Column(db.DateTime, default=datetime.now(),
                              onupdate=datetime.now())
    sity          = db.Column(db.String(80), default='', nullable=False)
    content       = db.Column(db.Text, default='', nullable=False)
    typograf      = db.Column(db.Text, default='', nullable=False)
    hash          = db.Column(db.String(40), default='', nullable=False)
    pub           = db.Column(db.Boolean, unique=False, default=False, nullable=False)
    mode          = db.Column(db.String(80), default='', nullable=False)

    def __init__(self, title, content, ovner) -> None:
        self.title = title
        self.content = content
        self.ovner = ovner
        self.hash = self.get_hash()

    def __str__(self):
        return f'Post: {self.title}'

    def __repr__(self):
        return f'Post: {self.title}'

    def set_title(self, title):
        self.title = title

    def set_content(self, content):
        self.content = content
        self.hash = sha1(bytes(content, encoding='utf8')).hexdigest()

    def set_pub_date(self, pub_date):
        self.pub_date = datetime.fromisoformat(pub_date).replace(microsecond=0)

    def set_sity(self, sity):
        self.sity = sity

    def set_forward(self, forward):
        self.forward = forward

    def set_archive(self):
        self.forward = 3

    def get_hash(self):
        return sha1(bytes(self.content, encoding='utf8')).hexdigest()

    def set_mode(self, mode):
        self.mode = mode

app/posts/routes.py
"""
    routers.py
"""

from datetime import datetime
from flask import Blueprint, render_template, request, url_for, flash, redirect
from flask_login import login_required, current_user
from flask_paginate import Pagination
from .models import Post
from app import db


DATE_FORMAT = '%d %B %Y %H:%M'
PER_PAGE = 15

# Blueprint Configuration
main = Blueprint(
    'main', __name__,
    template_folder='templates'
)

@main.route('/', methods=['GET'])
# @main.route('/index', methods=['GET'])
def index():
    """ Index Page """
    page = request.args.get('page', 1, type=int)
    posts = Post.query.\
        filter(Post.forward<2).\
        filter(Post.pub_date >= datetime.now().date()).\
        order_by(Post.pub_date.asc()).\
        paginate(page, PER_PAGE, False)

    pagination = Pagination(
        page=page,
        per_page=PER_PAGE,
        total=posts.total,
        record_name="posts",
        format_total=True,
        format_number=True,
    )

    return render_template('index.html', posts=posts.items,
                           pagination=pagination)

@main.route('/<int:post_id>')
def post(post_id):
    """ Show Post """
    post = Post.query.filter_by(id=post_id).first_or_404()
    return render_template('post.html', post=post,
                           last_modified = post.last_modified.strftime(DATE_FORMAT))

@main.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    """ Create new Post """
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            flash('Title is required!')
        else:
            new_post = Post(title=title, content=content, ovner=current_user.id)
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('main.index'))

    return render_template('create.html')

@main.route('/<int:id>/edit', methods=('GET', 'POST'))
@login_required
def edit(id):
    """ Edit Post """
    post = db.session.get(Post, id)

    if current_user.id <= post.ovner:

        if request.method == 'POST':
            title = request.form['title']
            content = request.form['content']
            pub_date = request.form['pub_date']
            if 'forward' in request.form:
                forward  = True
            else:
                forward  = False

            if not title:
                flash('Title is required!')
            else:
                post.set_title(title)
                post.set_content(content)
                post.set_pub_date(pub_date)
                post.set_forward(forward)
                db.session.commit()
                return redirect(url_for('main.index'))
    else:
        return redirect(url_for('main.profile'))

    return render_template('edit.html', post=post)

@main.route('/<int:id>/delete', methods=('POST','GET'))
@login_required
def delete(id):
    """ Delete Post """
    post = Post.query.get_or_404(id)
    if current_user.id <= post.ovner:
        db.session.delete(post)
        db.session.commit()
        flash('"{}" was successfully deleted!'.format(post))
    return redirect(url_for('main.index'))

@main.route('/profile')
@login_required
def profile():
    """ Show Profile curent User """
    return render_template('profile.html', user=current_user)

app/posts/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.index')}}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li> -->
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.create')}}">New Post</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('main.profile') }}" class="nav-link">Profile</a>
                </li>
                {% endif %}
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
                </li>
                <!-- <li class="nav-item">
                    <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                </li> -->
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/posts/templates/create.html
{% extends 'base.html' %}

{% block content %}
<h2>{% block title %} Новый пост {% endblock %}</h2>

<form method="post">
    <div class="form-group row">
        <label for="title" class="col-sm-2 col-form-label">Заголовок</label>
        <div class="col-sm-10">
            <input type="text" name="title"
                placeholder="Заголовок" class="form-control"
                value="{{ request.form['title'] }}">
        </div>
    </div>

    <div class="form-group row">
        <label for="pub_date" class="col-sm-2 col-form-label">Дата публикации</label>
        <div class="col-sm-10">
            <input type="datetime-local" id="pub_date" placeholder="дата публикации"
                class="form-control"
                value="{{ request.form['pub_date'] }}">
        </div>
    </div>

    <div class="form-group">
        <label for="content">Текст</label>
        <textarea name="content" placeholder="Текст"
            class="form-control" rows="12">{{ request.form['content'] }}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ url_for('main.index') }}">
            <span class="btn btn-primary">Отмена</span>
        </a>
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
</form>
{% endblock %}

app/posts/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<h2>Edit</h2>
<h4>{% block title %}{{ post['title'] }}{% endblock %}</h4>

<form method="post">
    <div class="form-group row">
        <label for="pub_date" class="col-sm-2 col-form-label">pub_date</label>
        <div class="col-sm-10">
            <input type="datetime-local" id="pub_date" name="pub_date" placeholder="Post pub_date"
                class="form-control"
                value="{{ request.form['pub_date'] or post['pub_date'] }}">
        </div>
    </div>

    <div class="form-group row">
        <label for="title" class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
            <input type="text" disabled
                    class="form-control" value="{{ request.form['title'] or post['title'] }}">
            <input type="hidden" name="title" placeholder="Post title"
                class="form-control"
                value="{{ request.form['title'] or post['title'] }}">
        </div>
    </div>

    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" placeholder="Post content"
                  class="form-control" rows="12">{{ request.form['content'] or post['content'] }}</textarea>
    </div>

    <div class="form-group">
        <label for="content">Preview</label>
        {{ post['content']|markdown }}
    </div>

    <div class="form-group">
        <input type="checkbox" name="forward" aria-label="публиковать" {% if request.form['forward'] or post['forward'] %}checked{% endif %}>
        <label for="title">публиковать</label>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <a href="{{ url_for('main.index') }}">
            <span class="btn btn-primary">Отмена</span>
        </a>
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
</form>
<hr>

<form action="{{ url_for('main.delete', id=post['id']) }}" method="POST">
    <input type="submit" value="Delete Post"
            class="btn btn-danger btn-sm"
            onclick="return confirm('Are you sure you want to delete this post?')">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
</form>

{% endblock %}

app/posts/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h2>{% block title %} Welcome to Blog {% endblock %}</h2>

    {{ pagination.info }}

    {{ pagination.links }}

    {% for post in posts %}
        <div class="container-fluid border border-secondary rounded p-3 m-1">
        {% if current_user.is_authenticated and current_user.id <= post.ovner %}
            <a href="{{ url_for('main.edit', id=post['id']) }}">
        {% else %}
            <a href="{{ url_for('main.post', post_id=post['id']) }}">
        {% endif %}
                <span class="text-capitalize font-weight-bold">{{ post['title'] }}</span>
            </a>

            <p class="mb-0">{{ post['mode'] }} | {{ post['sity'] }}</p>

            <span class="badge badge-primary col-2">{{ post.pub_date.strftime('%d %B %Y') }}</span>

        {% if current_user.is_authenticated and current_user.id <= post.ovner %}
            <a href="{{ url_for('main.edit', id=post['id']) }}">
                <span class="badge badge-success col-2">Edit</span>
            </a>
            <a href="{{ url_for('main.delete', id=post['id']) }}"
                onclick="return confirm('Are you sure you want to delete this post?')">
                <span class="badge badge-danger col-1">Delete</span>
            </a>
        {% endif %}

        {% if post['forward'] %}
            <span class="badge badge-success col-1">Да</span>
        {% else %}
            <span class="badge badge-light col-1">Нет</span>
        {% endif %}

        </div>
    {% endfor %}

    {{ pagination.links }}

{% endblock %}

app/posts/templates/login.html
<!-- templates/login.html -->

{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
    </div>
</div>
{% endblock %}

app/posts/templates/post.html
{% extends 'base.html' %}

{% block content %}
    <h2>Title: {% block title %}{{ post['title'] }}{% endblock %}</h2>
    <b>Last Modified:</b> <span class="badge badge-primary">{{ last_modified }}</span>
    <div><b>Content:</b>
        {{ post['content']|markdown }}
    </div>
    <div><b>Sity:</b> {{ post['sity'] }}</div>
    <div><b>pub_date:</b> {{ post['pub_date'] }}</div>
    <div><b>forward:</b> {{ post['forward'] }}</div>
{% endblock %}

app/posts/templates/profile.html
<!-- templates/profile.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ user.username }}!
</h1>
<p>id:{{ user.id }}</p>
<p>email:{{ user.email }}</p>
{% endblock %}

app/posts/templates/signup.html
<!-- templates/signup.html -->

{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
    </div>
</div>
{% endblock %}