app/auth.py
""" auth.py """

from flask import Blueprint, render_template, redirect, url_for, request, flash
# from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required
from .models import User

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    """ Render Form For Authorize user """
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    """ Authorize user """
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to
    # the hashed password in database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
         # if user doesn't exist or password is wrong, reload the page
        return redirect(url_for('auth.login'))

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.index'))

@auth.route('/signup')
def signup():
    """ Render Form For Create New User """
    return redirect(url_for('main.index'))

# @auth.route('/signup', methods=['POST'])
# def signup_post():
#     """ Create New User """
#     email    = request.form.get('email')
#     username = request.form.get('username')
#     password = request.form.get('password')

#     # if this returns a user, then the email already exists in database
#     user = User.query.filter_by(email=email).first()

#     # if a user is found, we want to redirect back to signup
#     # page so user can try again
#     if user:
#         flash('Email address already exists')
#         return redirect(url_for('auth.signup'))

#     # create new user with the form data. Hash the password so plaintext
#     # version isn't saved.
#     new_user = User(email=email, username=username,
#         password=generate_password_hash(password, method='sha256'))

#     # add the new user to the database
#     db.session.add(new_user)
#     db.session.commit()

#     return redirect(url_for('main.profile'))

@auth.route('/logout')
@login_required
def logout():
    """ Logout """
    logout_user()
    return redirect(url_for('main.index'))

app/main.py
"""
    main.py
"""

from flask import Blueprint, render_template, request, url_for, flash, redirect
from flask_login import login_required, current_user
from .models import Post
from . import db, date_format

main = Blueprint('main', __name__)

@main.route('/', methods=['GET'])
@main.route('/index', methods=['GET'])
def index():
    """ Index Page """
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.pub_date.asc()).paginate(page, 15, False)
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None

    return render_template('index.html', posts=posts.items,
                           next_url=next_url, prev_url=prev_url)

@main.route('/<int:post_id>')
def post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    return render_template('post.html', post=post, last_modified = post.last_modified.strftime(date_format))

@main.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            flash('Title is required!')
        else:
            new_post = Post(title=title, content=content, ovner=current_user.id)
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('main.index'))

    return render_template('create.html')

@main.route('/<int:id>/edit', methods=('GET', 'POST'))
@login_required
def edit(id):
    post = db.session.get(Post, id)

    if current_user.id == post.ovner:

        if request.method == 'POST':
            title = request.form['title']
            content = request.form['content']
            pub_date = request.form['pub_date']
            if 'forward' in request.form:
                forward  = True
            else:
                forward  = False

            if not title:
                flash('Title is required!')
            else:
                post.set_title(title)
                post.set_content(content)
                post.set_pub_date(pub_date)
                post.set_forward(forward)
                db.session.commit()
                return redirect(url_for('main.index'))
    else:
        return redirect(url_for('main.profile'))

    return render_template('edit.html', post=post)

@main.route('/<int:id>/delete', methods=('POST','GET'))
@login_required
def delete(id):
    post = Post.query.get_or_404(id)
    if current_user.id == post.ovner:
        db.session.delete(post)
        db.session.commit()
        flash('"{}" was successfully deleted!'.format(post))
    return redirect(url_for('main.index'))

@main.route('/profile')
@login_required
def profile():
    return render_template('profile.html', user=current_user)

if __name__ == '__main__':
    main.run(debug=True, host='0.0.0.0')

app/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.index')}}">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <!-- <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li> -->
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.create')}}">New Post</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('main.profile') }}" class="nav-link">Profile</a>
                </li>
                {% endif %}
                {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
                </li>
                <!-- <li class="nav-item">
                    <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                </li> -->
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>